//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class aile_bireyleri
    {
        public int aile_id { get; set; }
        public int personel_id { get; set; }
        public string yakinlik_derecesi { get; set; }
        public string ad_soyad { get; set; }
        public string tc_kimlik_no { get; set; }
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public Nullable<bool> calisiyor_mu { get; set; }
        public Nullable<bool> okuyor_mu { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
