//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class araclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public araclar()
        {
            this.arac_hareketleri = new HashSet<arac_hareketleri>();
        }
    
        public int arac_id { get; set; }
        public string plaka { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public Nullable<int> yil { get; set; }
        public string yakit_tipi { get; set; }
        public Nullable<bool> kiralik_mi { get; set; }
        public Nullable<int> zimmetli_personel_id { get; set; }
        public Nullable<int> son_km { get; set; }
        public Nullable<System.DateTime> muayene_bitis_tarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arac_hareketleri> arac_hareketleri { get; set; }
    }
}
