//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class arac_hareketleri
    {
        public int log_id { get; set; }
        public int arac_id { get; set; }
        public int personel_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public int alinan_km { get; set; }
        public int birakilan_km { get; set; }
        public string gidilen_guzergah { get; set; }
        public string aciklama { get; set; }
    
        public virtual araclar araclar { get; set; }
        public virtual personeller personeller { get; set; }
    }
}
