//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class avanslar
    {
        public int avans_id { get; set; }
        public int personel_id { get; set; }
        public Nullable<System.DateTime> talep_tarihi { get; set; }
        public decimal tutar { get; set; }
        public System.DateTime istenen_odeme_tarihi { get; set; }
        public Nullable<byte> onay_durumu { get; set; }
        public Nullable<System.DateTime> kesilecek_maas_donemi { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
