//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class bordrolar
    {
        public int bordro_id { get; set; }
        public int personel_id { get; set; }
        public int yil { get; set; }
        public int ay { get; set; }
        public Nullable<decimal> normal_calisma_gun { get; set; }
        public Nullable<decimal> ucretli_izin_gun { get; set; }
        public Nullable<decimal> ucretsiz_izin_gun { get; set; }
        public Nullable<decimal> raporlu_gun { get; set; }
        public Nullable<decimal> fazla_mesai_saati { get; set; }
        public Nullable<decimal> brut_ucret { get; set; }
        public Nullable<decimal> sgk_primi { get; set; }
        public Nullable<decimal> vergi_kesintisi { get; set; }
        public Nullable<decimal> avans_kesintisi { get; set; }
        public Nullable<decimal> ek_odeme_prim { get; set; }
        public Nullable<decimal> net_odenen { get; set; }
        public Nullable<bool> bordro_kesildi_mi { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
