//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class demirbaslar
    {
        public int demirbas_id { get; set; }
        public string kategori { get; set; }
        public string marka_model { get; set; }
        public string seri_no { get; set; }
        public Nullable<System.DateTime> alim_tarihi { get; set; }
        public Nullable<System.DateTime> garanti_bitis { get; set; }
        public Nullable<int> personel_id { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
