//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class departmanlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public departmanlar()
        {
            this.personellers = new HashSet<personeller>();
            this.pozisyonlars = new HashSet<pozisyonlar>();
        }
    
        public int departman_id { get; set; }
        public int sube_id { get; set; }
        public string departman_adi { get; set; }
        public Nullable<int> ust_departman_id { get; set; }
        public string masraf_kodu { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> aktif_mi { get; set; }
    
        public virtual subeler subeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personeller> personellers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pozisyonlar> pozisyonlars { get; set; }
    }
}
