//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class dil_cevirileri
    {
        public int ceviri_id { get; set; }
        public string anahtar { get; set; }
        public string dil_kodu { get; set; }
        public string deger { get; set; }
    
        public virtual dil_tanimlari dil_tanimlari { get; set; }
    }
}
