//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class disiplin_kayitlari
    {
        public int kayit_id { get; set; }
        public int personel_id { get; set; }
        public System.DateTime tarih { get; set; }
        public string olay_ozeti { get; set; }
        public string verilen_ceza { get; set; }
        public string savunma_dosyasi { get; set; }
        public Nullable<System.DateTime> karar_tarihi { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
