//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class egitimler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public egitimler()
        {
            this.personel_egitimleri = new HashSet<personel_egitimleri>();
        }
    
        public int egitim_id { get; set; }
        public string egitim_adi { get; set; }
        public string kurum { get; set; }
        public string konu { get; set; }
        public Nullable<int> gecerlilik_suresi_yil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel_egitimleri> personel_egitimleri { get; set; }
    }
}
