//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class izinler
    {
        public int izin_id { get; set; }
        public int personel_id { get; set; }
        public int tur_id { get; set; }
        public System.DateTime baslangic { get; set; }
        public System.DateTime bitis { get; set; }
        public decimal gun_sayisi { get; set; }
        public string adres_telefon { get; set; }
        public Nullable<int> onay_durumu { get; set; }
        public string red_sebebi { get; set; }
    
        public virtual izin_turleri izin_turleri { get; set; }
        public virtual personeller personeller { get; set; }
    }
}
