//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kariyer_hareketleri
    {
        public int hareket_id { get; set; }
        public int personel_id { get; set; }
        public System.DateTime tarih { get; set; }
        public Nullable<int> eski_departman_id { get; set; }
        public int yeni_departman_id { get; set; }
        public Nullable<int> eski_pozisyon_id { get; set; }
        public int yeni_pozisyon_id { get; set; }
        public Nullable<decimal> eski_maas { get; set; }
        public Nullable<decimal> yeni_maas { get; set; }
        public string aciklama { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
