//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanicilar
    {
        public int kullanici_id { get; set; }
        public int personel_id { get; set; }
        public string kullanici_adi { get; set; }
        public string sifre_hash { get; set; }
        public string rol_yetkisi { get; set; }
        public Nullable<bool> aktif_mi { get; set; }
        public Nullable<System.DateTime> son_giris { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
