//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class maas_bordro
    {
        public int bordro_id { get; set; }
        public int personel_id { get; set; }
        public int yil { get; set; }
        public int ay { get; set; }
        public Nullable<decimal> brut_maas { get; set; }
        public Nullable<decimal> primler { get; set; }
        public Nullable<decimal> kesintiler { get; set; }
        public Nullable<decimal> net_odenen { get; set; }
        public Nullable<System.DateTime> odeme_tarihi { get; set; }
        public Nullable<bool> durum { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
