//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesailer
    {
        public int mesai_id { get; set; }
        public int personel_id { get; set; }
        public System.DateTime baslangic_saati { get; set; }
        public System.DateTime bitis_saati { get; set; }
        public decimal toplam_saat { get; set; }
        public decimal saat_ucreti { get; set; }
        public decimal toplam_tutar { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string aciklama { get; set; }
        public Nullable<bool> onay_durumu { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
