//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pdks_hareketleri
    {
        public long hareket_id { get; set; }
        public int personel_id { get; set; }
        public Nullable<System.DateTime> zaman_damgasi { get; set; }
        public string hareket_tipi { get; set; }
        public string terminal_kodu { get; set; }
    
        public virtual personeller personeller { get; set; }
    }
}
