//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class personeller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personeller()
        {
            this.aile_bireyleri = new HashSet<aile_bireyleri>();
            this.arac_hareketleri = new HashSet<arac_hareketleri>();
            this.avanslars = new HashSet<avanslar>();
            this.bordrolars = new HashSet<bordrolar>();
            this.demirbaslars = new HashSet<demirbaslar>();
            this.disiplin_kayitlari = new HashSet<disiplin_kayitlari>();
            this.izinlers = new HashSet<izinler>();
            this.kariyer_hareketleri = new HashSet<kariyer_hareketleri>();
            this.kullanicilars = new HashSet<kullanicilar>();
            this.pdks_hareketleri = new HashSet<pdks_hareketleri>();
            this.personel_egitimleri = new HashSet<personel_egitimleri>();
            this.personel_vardiyalari = new HashSet<personel_vardiyalari>();
            this.maas_bordro = new HashSet<maas_bordro>();
            this.mesailers = new HashSet<mesailer>();
        }
    
        public int personel_id { get; set; }
        public string tc_kimlik_no { get; set; }
        public string sicil_no { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string uyruk { get; set; }
        public string cinsiyet { get; set; }
        public Nullable<System.DateTime> dogum_tarihi { get; set; }
        public string dogum_yeri { get; set; }
        public string kan_grubu { get; set; }
        public string medeni_hal { get; set; }
        public string email_sirket { get; set; }
        public string email_kisisel { get; set; }
        public string cep_telefonu { get; set; }
        public string ev_telefonu { get; set; }
        public string ikametgah_adresi { get; set; }
        public int sube_id { get; set; }
        public int departman_id { get; set; }
        public int pozisyon_id { get; set; }
        public Nullable<int> yonetici_id { get; set; }
        public System.DateTime ise_giris_tarihi { get; set; }
        public string sozlesme_turu { get; set; }
        public string calisma_durumu { get; set; }
        public Nullable<System.DateTime> ayrilis_tarihi { get; set; }
        public string ayrilis_nedeni { get; set; }
        public string maas_tipi { get; set; }
        public Nullable<decimal> ucret { get; set; }
        public string banka_adi { get; set; }
        public string iban { get; set; }
        public Nullable<int> engellilik_orani { get; set; }
        public Nullable<bool> hukumlu_mu { get; set; }
        public Nullable<bool> teror_magduru_mu { get; set; }
        public string resim_yolu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aile_bireyleri> aile_bireyleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<arac_hareketleri> arac_hareketleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<avanslar> avanslars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bordrolar> bordrolars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<demirbaslar> demirbaslars { get; set; }
        public virtual departmanlar departmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disiplin_kayitlari> disiplin_kayitlari { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<izinler> izinlers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kariyer_hareketleri> kariyer_hareketleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kullanicilar> kullanicilars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pdks_hareketleri> pdks_hareketleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel_egitimleri> personel_egitimleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel_vardiyalari> personel_vardiyalari { get; set; }
        public virtual pozisyonlar pozisyonlar { get; set; }
        public virtual subeler subeler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<maas_bordro> maas_bordro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mesailer> mesailers { get; set; }
    }
}
