//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel_egitimleri
    {
        public int kayit_id { get; set; }
        public int personel_id { get; set; }
        public int egitim_id { get; set; }
        public System.DateTime tarih { get; set; }
        public Nullable<int> puan { get; set; }
        public string sertifika_dosya { get; set; }
    
        public virtual egitimler egitimler { get; set; }
        public virtual personeller personeller { get; set; }
    }
}
