//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonelTakipSistemiDBEntities : DbContext
    {
        public PersonelTakipSistemiDBEntities()
            : base("name=PersonelTakipSistemiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aile_bireyleri> aile_bireyleri { get; set; }
        public virtual DbSet<arac_hareketleri> arac_hareketleri { get; set; }
        public virtual DbSet<araclar> araclars { get; set; }
        public virtual DbSet<avanslar> avanslars { get; set; }
        public virtual DbSet<bordrolar> bordrolars { get; set; }
        public virtual DbSet<demirbaslar> demirbaslars { get; set; }
        public virtual DbSet<departmanlar> departmanlars { get; set; }
        public virtual DbSet<disiplin_kayitlari> disiplin_kayitlari { get; set; }
        public virtual DbSet<egitimler> egitimlers { get; set; }
        public virtual DbSet<izin_turleri> izin_turleri { get; set; }
        public virtual DbSet<izinler> izinlers { get; set; }
        public virtual DbSet<kariyer_hareketleri> kariyer_hareketleri { get; set; }
        public virtual DbSet<kullanicilar> kullanicilars { get; set; }
        public virtual DbSet<pdks_hareketleri> pdks_hareketleri { get; set; }
        public virtual DbSet<personel_egitimleri> personel_egitimleri { get; set; }
        public virtual DbSet<personel_vardiyalari> personel_vardiyalari { get; set; }
        public virtual DbSet<personeller> personellers { get; set; }
        public virtual DbSet<pozisyonlar> pozisyonlars { get; set; }
        public virtual DbSet<sistem_ayarlari> sistem_ayarlari { get; set; }
        public virtual DbSet<sistem_loglari> sistem_loglari { get; set; }
        public virtual DbSet<subeler> subelers { get; set; }
        public virtual DbSet<vardiya_tanimlari> vardiya_tanimlari { get; set; }
        public virtual DbSet<dil_cevirileri> dil_cevirileri { get; set; }
        public virtual DbSet<dil_tanimlari> dil_tanimlari { get; set; }
        public virtual DbSet<maas_bordro> maas_bordro { get; set; }
        public virtual DbSet<mesailer> mesailers { get; set; }
    }
}
