//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pozisyonlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pozisyonlar()
        {
            this.personellers = new HashSet<personeller>();
        }
    
        public int pozisyon_id { get; set; }
        public int departman_id { get; set; }
        public string pozisyon_adi { get; set; }
        public Nullable<int> yetki_kodu { get; set; }
        public Nullable<bool> overtime_hakki_var_mi { get; set; }
        public Nullable<bool> aktif_mi { get; set; }
    
        public virtual departmanlar departmanlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personeller> personellers { get; set; }
    }
}
