//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class sistem_loglari
    {
        public long log_id { get; set; }
        public Nullable<int> kullanici_id { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string tablo_adi { get; set; }
        public string islem_tipi { get; set; }
        public string eski_veri_json { get; set; }
        public string yeni_veri_json { get; set; }
        public string ip_adresi { get; set; }
    }
}
