//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personel_Takip_Sistemi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vardiya_tanimlari
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vardiya_tanimlari()
        {
            this.personel_vardiyalari = new HashSet<personel_vardiyalari>();
        }
    
        public int vardiya_id { get; set; }
        public string vardiya_adi { get; set; }
        public System.TimeSpan baslangic_saati { get; set; }
        public System.TimeSpan bitis_saati { get; set; }
        public Nullable<int> mola_suresi_dk { get; set; }
        public Nullable<decimal> erken_mesai_carpan { get; set; }
        public Nullable<bool> gece_zammi_var_mi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personel_vardiyalari> personel_vardiyalari { get; set; }
    }
}
